services:
  db:
    platform: linux/amd64
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 12

  web:
    platform: linux/amd64
    build: .
    command: bash -lc "bundle _1.16.1_ exec rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      RAILS_LOG_TO_STDOUT: "true"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
